"use client";

import { useMemo } from "react";
import { StudentFormValues, StudentMeta } from "./student-types";

type Props = {
  value: StudentFormValues;
  meta: StudentMeta | null;
  onChange: (next: StudentFormValues) => void;
  onSubmit: () => void;
  submitLabel: string;
  includePassword?: boolean;
  loading?: boolean;
};

export default function StudentForm({
  value,
  meta,
  onChange,
  onSubmit,
  submitLabel,
  includePassword = true,
  loading = false,
}: Props) {
  const programs = useMemo(() => {
    if (!meta) return [];
    if (!value.departmentId) return meta.programs;
    return meta.programs.filter(
      (p) => String(p.department_id) === value.departmentId,
    );
  }, [meta, value.departmentId]);

  const update = (key: keyof StudentFormValues, nextValue: string) => {
    onChange({ ...value, [key]: nextValue });
  };

  return (
    <div className="bg-[#FCFBF8] rounded-xl border border-[#E7E2D9] shadow-sm p-6 space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <input
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          placeholder="First name"
          value={value.firstName}
          onChange={(e) => update("firstName", e.target.value)}
        />
        <input
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          placeholder="Last name"
          value={value.lastName}
          onChange={(e) => update("lastName", e.target.value)}
        />
        <input
          className="border border-[#DED7CB] bg-gray-100 rounded-lg p-2"
          placeholder="Email"
          type="email"
          value={value.email}
          readOnly
        />
        {includePassword && (
          <input
            className="border border-[#DED7CB] bg-gray-100 rounded-lg p-2"
            placeholder="Password"
            type="text"
            value={value.password}
            readOnly
          />
        )}
        <input
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          placeholder="Phone"
          value={value.phone}
          onChange={(e) => update("phone", e.target.value)}
        />

        <select
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          value={value.departmentId}
          onChange={(e) => update("departmentId", e.target.value)}
        >
          <option value="">Select department</option>
          {meta?.departments.map((d) => (
            <option key={d.department_id} value={d.department_id}>
              {d.department_name}
            </option>
          ))}
        </select>

        <select
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          value={value.programId}
          onChange={(e) => update("programId", e.target.value)}
        >
          <option value="">Select program</option>
          {programs.map((p) => (
            <option key={p.program_id} value={p.program_id}>
              {p.program_name}
            </option>
          ))}
        </select>

        <input
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          placeholder="Enrollment year"
          type="number"
          value={value.enrollmentYear}
          onChange={(e) => update("enrollmentYear", e.target.value)}
        />
        <input
          className="border border-[#DED7CB] bg-white rounded-lg p-2"
          placeholder="Semester"
          type="number"
          value={value.semester}
          onChange={(e) => update("semester", e.target.value)}
        />
      </div>
      <p className="text-sm text-gray-600">
        Email and password are auto-generated by the system.
      </p>

      <button
        onClick={onSubmit}
        disabled={loading}
        className="bg-[#7A263A] text-white px-4 py-2 rounded-lg hover:bg-[#631F2F] disabled:opacity-60"
      >
        {loading ? "Saving..." : submitLabel}
      </button>
    </div>
  );
}
